info:
  component: Config Server

spring:
  pidfile: configsrv.pid
  application:
    name: configsrv
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/repo

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://mandrel:MAndR3L@${eureka.instance.hostname}:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
  dashboard:
    enabled: true
    path: /eureka

#security:
#  user:
#    name: mandrel
#    password: MAndR3L

server:
  port: 8900

management:
  context_path: /admin

endpoints:
  restart:
    enabled: true

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG